@host=http://localhost:3001

###
GET {{host}}/autor

###
GET {{host}}/autor/4

###
POST {{host}}/autor/
Content-Type: application/json

{
  "nome": "Alisson",
  "email": "al@gmail.com",
  "telefone": "41-012365"
}

###
PUT {{host}}/autor
Content-Type: application/json

{
  "autor_id": 41,
  "nome": "Alisson da Silva",
  "email": "al@gmail.com",
  "telefone": "44-123654"
}

###
DELETE {{host}}/autor/