##
# Gerar credenciais no bash:
# echo -n admin:desafio-igti-nodejs | base64
##

@host=http://localhost:3001

###
GET {{host}}/autor
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

###
GET {{host}}/autor/4
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==


###
POST {{host}}/autor/
Content-Type: application/json
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

{
  "nome": "Alisson",
  "email": "al@gmail.com",
  "telefone": "41-012365"
}

###
PUT {{host}}/autor
Content-Type: application/json
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

{
  "autor_id": 41,
  "nome": "Alisson da Silva",
  "email": "al@gmail.com",
  "telefone": "44-123654"
}

###
DELETE {{host}}/autor/4
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==
