##
# Gerar credenciais no bash:
# echo -n admin:desafio-igti-nodejs | base64
##

@host=http://localhost:3001

###
GET {{host}}/livro
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

###
GET {{host}}/livro?autor_id=2
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

###
GET {{host}}/livro?autorId=7
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

###
GET {{host}}/livro/5
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

###
POST {{host}}/livro
Content-Type: application/json
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

{
  "nome": "Vinte mil léguas submarinas",
  "valor": 11,
  "estoque": 1,
  "autor_id": 1
}

###
PUT {{host}}/livro
Content-Type: application/json
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

{
  "livro_id": 7,
  "nome": "Vinte mil léguas submarinas II",
  "valor": 11.55,
  "estoque": 8,
  "autor_id": 1
}

###
DELETE {{host}}/livro/7
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

###
POST {{host}}/livro/info
Content-Type: application/json
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

{
  "livroId": 7,
  "descricao": "um livro bem bacana",
  "paginas": 130,
  "editora": "vai cai"
}

###
PUT {{host}}/livro/info
Content-Type: application/json
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

{
  "livroId": 6,
  "descricao": "um baita livro",
  "paginas": 215,
  "editora": "num vem"
}

###
DELETE {{host}}/livro/info/6
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

###
POST {{host}}/livro/6/avaliacao
Content-Type: application/json
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

{
  "nome": "Atauã",
  "nota": 8,
  "avaliacao": "É divertido!"
}

###
DELETE {{host}}/livro/6/avaliacao/0
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==
