@host=http://localhost:3001

###
GET {{host}}/livro

###
GET {{host}}/livro?autor_id=2

###
GET {{host}}/livro?autorId=7

###
GET {{host}}/livro/5

###
POST {{host}}/livro
Content-Type: application/json

{
  "nome": "Vinte mil léguas submarinas",
  "valor": 11,
  "estoque": 1,
  "autor_id": 1
}

###
PUT {{host}}/livro
Content-Type: application/json

{
  "livro_id": 7,
  "nome": "Vinte mil léguas submarinas II",
  "valor": 11.55,
  "estoque": 8,
  "autor_id": 1
}

###
DELETE {{host}}/livro/7

###
POST {{host}}/livro/info
Content-Type: application/json

{
  "livroId": 7,
  "descricao": "um livro bem bacana",
  "paginas": 130,
  "editora": "vai cai"
}

###
PUT {{host}}/livro/info
Content-Type: application/json

{
  "livroId": 6,
  "descricao": "um baita livro",
  "paginas": 215,
  "editora": "num vem"
}

###
DELETE {{host}}/livro/info/6

###
POST {{host}}/livro/6/avaliacao
Content-Type: application/json

{
  "nome": "Atauã",
  "nota": 8,
  "avaliacao": "É divertido!"
}

###
DELETE {{host}}/livro/6/avaliacao/0