##
# Gerar credenciais no bash:
# echo -n admin:desafio-igti-nodejs | base64
##

@host=http://localhost:3001

###
GET {{host}}/venda
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

###
GET {{host}}/venda?livro_id=1
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

###
GET {{host}}/venda?cliente_id=1
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

###
GET {{host}}/venda?autor_id=3
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

###
GET {{host}}/venda/1
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

###
POST {{host}}/venda
Content-Type: application/json
Authorization: Basic YWRtaW46ZGVzYWZpby1pZ3RpLW5vZGVqcw==

{
  "data": "2022-01-20",
  "cliente_id": 2,
  "livro_id": 9
}