@host=http://localhost:3001

###
GET {{host}}/venda

###
GET {{host}}/venda?livro_id=1

###
GET {{host}}/venda?cliente_id=1

###
GET {{host}}/venda?autor_id=3

###
GET {{host}}/venda/1

###
POST {{host}}/venda
Content-Type: application/json

{
  "data": "2022-01-20",
  "cliente_id": 2,
  "livro_id": 9
}